#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)
#

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
        for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
                [ -x "$f" ] && . "$f"
        done
        unset f
fi

#~/scripts/keyboard.sh &
#~/scripts/file-inotify /tmp/keyboard.lock ~/scripts/keyboard.sh &

exec i3
