# Don't print a new line at the start of the prompt
add_newline = false

[line_break]
disabled = true

[rust]
symbol = " "
disabled = true

[aws]
disabled = true

[character]
success_symbol = "[❯](none)"

[cmd_duration]
min_time = 200
show_notifications = true
notification_timeout = 30000

# Disable the package module, hiding it from the prompt completely
#[package]
#disabled = true
