# Don't print a new line at the start of the prompt
add_newline = false

[line_break]
disabled = true

[rust]
symbol = " "
disabled = true

[character]
success_symbol = "[❯](none)"

# Disable the package module, hiding it from the prompt completely
#[package]
#disabled = true
